create table if not exists events (
  id serial primary key,
  name text not null unique,
  category text not null default 'general',
  created_at timestamptz default now()
);

alter table events
  add column if not exists category text not null default 'general';

insert into events (name, category) values
  ('Une scene coupee est montree', 'coulisses'),
  ('Une photo backstage est revelee', 'coulisses'),
  ('Une anecdote genante est racontee', 'coulisses'),
  ('Une anecdote sur un echec', 'coulisses'),
  ('Revelation d un moment de tournage rate', 'coulisses'),
  ('Explication d un decor bricole', 'coulisses'),
  ('Mention d un ancien projet rate', 'coulisses'),
  ('Un acteur absent est mentionne', 'coulisses'),
  ('Lecture d un dialogue', 'creative'),
  ('Lecture d une version alternative d une scene', 'creative'),
  ('Debat sur le titre', 'creative'),
  ('Pitch absurde du film', 'creative'),
  ('Pitch version blockbuster', 'creative'),
  ('Pitch version film d auteur', 'creative'),
  ('L equipe defend une blague critiquee', 'creative'),
  ('Comparaison absurde avec un gros film', 'creative'),
  ('Une reference assumee', 'creative'),
  ('Une reference honteuse', 'creative'),
  ('Une fausse bande annonce improvisee', 'creative'),
  ('L humoriste propose un nouveau titre', 'creative'),
  ('Vote sur un element creatif', 'creative'),
  ('Une replique est jouee en 3 versions differentes', 'creative'),
  ('Une scene est jouee au ralenti', 'creative'),
  ('Une scene est jouee trop vite', 'creative'),
  ('Une scene est jouee sans paroles', 'creative'),
  ('Le chat spam un emoji', 'chat'),
  ('Le chat pose la meme question 3 fois', 'chat'),
  ('Un commentaire troll est lu', 'chat'),
  ('Un commentaire ultra positif est lu', 'chat'),
  ('Quelqu un ecrit en majuscules', 'chat'),
  ('Le moderateur intervient', 'chat'),
  ('Le lien est redemande dans le chat', 'chat'),
  ('Quelqu un ecrit je viens de donner', 'chat'),
  ('Quelqu un ecrit c est fait', 'chat'),
  ('Quelqu un ecrit je re donne', 'chat'),
  ('La salle se leve', 'public'),
  ('Standing ovation', 'public'),
  ('Applaudissements spontanes', 'public'),
  ('Applaudissements trop longs', 'public'),
  ('Le public scande quelque chose', 'public'),
  ('Le public rit plus fort que prevu', 'public'),
  ('Un membre du public pose une question', 'public'),
  ('Un membre du public interpelle le plateau', 'public'),
  ('Un membre du public donne en direct', 'public'),
  ('Un selfie collectif', 'public'),
  ('L humoriste descend dans la salle', 'public'),
  ('Le public vote a main levee', 'public'),
  ('Le public hue gentiment', 'public'),
  ('Quelqu un dans le public crie un prenom', 'public'),
  ('La salle compte a rebours', 'public'),
  ('La salle tape des pieds', 'public'),
  ('La salle fait OHHHH en choeur', 'public'),
  ('La salle improvise un chant', 'public'),
  ('Un membre du public devient complice d une impro', 'public'),
  ('Un accessoire tombe', 'public'),
  ('Une chaise grince fort', 'public'),
  ('Quelqu un rit trop fort', 'public'),
  ('Cloche des dons sonnee', 'dons'),
  ('3 dons arrivent en moins d 1 minute', 'dons'),
  ('5 dons arrivent en moins de 2 minutes', 'dons'),
  ('10 dons cumules depuis le debut du live', 'dons'),
  ('Un don superieur a 50 EUR', 'dons'),
  ('Un don superieur a 100 EUR', 'dons'),
  ('Deux dons superieurs a 100 EUR a moins de 3 minutes d ecart', 'dons'),
  ('Un don arrive pendant un fou rire', 'dons'),
  ('Un don arrive pendant un silence genant', 'dons'),
  ('Le compteur fait un bond visible', 'dons'),
  ('Deux dons consecutifs', 'dons'),
  ('Trois dons consecutifs', 'dons'),
  ('Un don d un membre du studio', 'dons'),
  ('Un don arrive pile pendant une impro', 'dons'),
  ('Un don arrive pendant que l humoriste parle', 'dons'),
  ('Un don declenche une cloche', 'dons'),
  ('Un don est lu a voix haute', 'dons'),
  ('Un message de don particulierement long', 'dons'),
  ('Un message de don particulierement absurde', 'dons'),
  ('Un don avec un pseudo drole', 'dons'),
  ('Un don avec un prenom identique a quelqu un sur le plateau', 'dons'),
  ('Un don venu de l etranger', 'dons')
on conflict (name) do update set category = excluded.category;
